male:
  name: 佚名  # 姓名
  id: '00000000000000000X'  # 身份证号
  phone: '00000000000'  # 手机号
  # 学历,请从以下选项输入
  # 文盲或半文盲、小学、初中、高中、中专、大专、大学、硕士研究生、博士研究生
  education: 大学
  # 职业,请从以下选项输入
  # '国家机关，党群组织，企事业单位'
  # '商业、服务业人员'
  # '生产、运输设备操作人员及有关人员'
  # '办事人员和有关人员'
  # '农、林、牧、渔、水利业生产人员'
  # '军人'
  # '专业技术人员'
  # '无业人员'
  # '其他从业人员'
  occupation: 军人
female:
  name: 佚名
  id: '00000000000000000X'
  phone: '00000000000'
  education: 大学
  occupation: 军人

# 本项目使用Server酱推送通知，请填写你的Send KEY
# 申请地址：https://sct.ftqq.com
# https://sctapi.ftqq.com/<SENDKEY>.send
ft_send_key: SC0000000000000000000

# 日志等级，可选 DEBUG, INFO, WARNING, ERROR, CRITICAL
log_level: INFO

# 城市，仅广东省内可用，不需要加 “市” 字
city: 深圳  

# 区县镇，无须加 “区|镇|县” 字
areas:
  - 南山
  - 福田
  - 大鹏

# 想要预约的日期，格式为 YYYY-MM-DD
# 注意仅有部分民政局周六开放，所有民政局周日均不开放
date: '2023-06-27'

# www.ttshitu.com识图平台账号密码
ttshitu:
  username: xxxxxxx  # 图鉴账号
  password: yyyyyy  # 图鉴密码
  # 识别类型,详见http://www.ttshitu.com/docs/index.html
  type_id: 1003  # 1003为数英混合2，如果准确率不高，可以尝试更换识别类型

headless: false  # 是否使用无头模式，如果你的服务器没有图形界面，请设置为true
